import Head from "next/head";
import React, { useEffect, useState } from "react";

import {
  QueryClient,
  QueryClientProvider,
  useIsFetching,
} from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

import { WeatherBody } from "@/components";
import Loading from "@/components/Loading";

export default function Home() {
  const [badRequest, setBadRequest] = useState<boolean>(false);
  const [loading, setLoading] = useState<boolean>(true);

  const queriesClient = new QueryClient();


  
  useEffect(() => {
    setLoading(() => false)
  }, []);
  
  // if (loading) return <Loading />;

  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <QueryClientProvider client={queriesClient}>
        <WeatherBody />
        <ReactQueryDevtools />
      </QueryClientProvider>
    </>
  );
}
